data:
  dev_path: ./data/val_preprocessed.csv
  model_path: ./save_model/klue-roberta-large_Batch-size:64_Max-epochs:20_Multi-task:False_lr:5e-06_siamese:False/model.pt
  output_path: ./output/
  predict_path: ./data/test_preprocessed.csv
  save_path: null
  submission_path: ./data/sample_submission.csv
  test_path: ./data/val_preprocessed.csv
  train_path: ./data/train_preprocessed_augmented.csv
model:
  layer_aggregate: true
  model_name: klue/roberta-large
  siamese: false
train:
  batch_size: 64
  fine_tuning_epoch: 3
  learning_rate: 5e-6
  loss_function: MSE
  max_epochs: 20
  multi_task: false
  shuffle: true
